[Vue] migrate select-variable directive to Vue
matomo-org/tag-manager pull request #406
Opened 2022-01-13 05:31 UTC by diosmosis

### Description:

**This PR is based on https://github.com/matomo-org/tag-manager/pull/404.**

Changes:
* migrate piwik-variable-select directive to Vue.
* start adding type definitions for TagManager entity types.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2022-02-01 15:25 UTC, sgiehl requested changes
Left some comments. Besides that it seems to work as expected.

2022-02-01 15:25 UTC, sgiehl commented on vue/src/VariableSelect/VariableSelect.vue
> +        <span class="title">{{ variable.name }} (Type: {{ variable.type }})</span>
We could maybe directly use the translation here, even though it was missing before ;-)

```suggestion
        <span class="title">{{ variable.name }} ({{ translate('TagManager_Type') }}: {{ variable.type }})</span>
```

2022-02-01 15:25 UTC, sgiehl commented on vue/src/VariableSelect/VariableSelect.vue
> +            @click.prevent="editVariable(variable)"
Seems the `prevent` doesn't work as expected here. When clicking the edit icon, the edit dialog opens, but the variable is also selected in the background, which wasn't the case before.

2022-02-03 15:50 UTC, diosmosis commented
@sgiehl applied the fixes

2022-02-07 10:37 UTC, sgiehl approved these changes

2022-02-07 10:37 UTC, merged