Added new option in Matomo Config Variable to disable Form and Media Analytics
matomo-org/tag-manager pull request #556
Opened 2022-10-19 08:25 UTC by AltamashShaikh

### Description:

Added new option in Matomo Config Variable to disable Form and Media Analytics.
Fixes: #PG-657

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2022-10-20 01:26 UTC, snake14 requested changes
Looks good and the functional testing went well once I remembered that I had to publish a new version after updating my configuration variable. However, I noticed that I had another configuration variable showing as changed when I hadn't changed it. I think that you need to created a migration and use `plugins/TagManager/Updates/NewTagParameterMigrator.php` or do something similar in order to add the new param to all existing config variables.

2022-10-20 07:31 UTC, AltamashShaikh commented
> Looks good and the functional testing went well once I remembered that I had to publish a new version after updating my configuration variable. However, I noticed that I had another configuration variable showing as changed when I hadn't changed it. I think that you need to create a migration and do something similar to `plugins/TagManager/Updates/NewTagParameterMigrator.php` in order to add the new params to all existing config variables.

@snake14 Added migration script,
To test it rename the file to `4.12.0-b1` and your version in the `option` table to `4.11.0` and give it a try, thats how I was able to test it

2022-10-20 21:55 UTC, snake14 requested changes
Looks good. I had to make one little change to get the functional test to work. Please see my inline comment.

2022-10-20 21:55 UTC, snake14 commented on Updates/NewVariableParameterMigrator.php
> +        $variableInfo = $this->variablesDao->getContainerVariable($idSite, $idVersion, $idVariable);
I had to add the following below this line in order to get it to run for all of my sites:
```
if (empty($variableInfo['parameters'])) {
        return;
}
```

Once I added that check, it updated the necessary variables and they no longer showed as changed when I went to publish a new version.

2022-10-21 02:08 UTC, AltamashShaikh commented on Updates/NewVariableParameterMigrator.php
> +        $variableInfo = $this->variablesDao->getContainerVariable($idSite, $idVersion, $idVariable);
@snake14 updated as suggested

2022-10-21 02:16 UTC, snake14 approved these changes
Looks good :+1:

2022-10-21 02:52 UTC, merged