Implemented setEcommerceView
matomo-org/tag-manager pull request #699
Opened 2023-10-09 19:31 UTC by EPNW-Eric

I thought Ecommerce support would be nice (at least to a certain extend) for the Tag Manager.
This PR focuses on the `setEcommerceView` of the Matomo Tracker.
Documentation is mostly copied from the corresponding function in [`piwik.js`](https://github.com/matomo-org/matomo/blob/8770cde10eafa3f9c22e3030b9ac33a26a175eff/js/piwik.js#L6958).
I'll open an seperate issue about my thoughts of the other ecommerce tracking functions.

Feedback and discussion is highly appreciated 😄.

2023-10-11 00:12 UTC, AltamashShaikh reviewed
Looks good to me, I will do a functional test and get back to you :+1:

2023-10-11 23:13 UTC, snake14 requested changes
Nice work! I only had few couple comments.

2023-10-11 23:13 UTC, snake14 commented on Updates/5.0.0-rc4.php
> +class Updates_5_0_0_rc4 extends PiwikUpdates
Matomo 5.0.0-rc4 has already been released. Could you please refactor this for 5.0.0-rc5?

2023-10-11 23:13 UTC, snake14 commented on lang/en.json
> +        "MatomoTagEcommerceViewPriceHelp": "Item's display price, not use in standard Matomo reports, but output in API product reports.",
Was this meant to say `used` instead of `use`?

2023-10-11 23:37 UTC, snake14 commented on Updates/5.0.0-rc4.php
> +        $migrator = new NewVariableParameterMigrator(MatomoTag::ID, 'isEcommerceView', false);
Can you please update this to use NewTagParameterMigrator instead, since you're adding parameters to a Tag and not a Variable?

2023-10-12 19:58 UTC, snake14 approved these changes
Thank you for making those changes. It looks good to me and I didn't find any issues during functional testing :+1:

2023-10-13 04:45 UTC, AltamashShaikh approved these changes

2023-10-13 04:45 UTC, merged