Add 'require consent for campaigns tracking' setting
matomo-org/tag-manager pull request #766
Opened 2024-03-13 06:46 UTC by michalkleiner

### Description:

Companion PR to https://github.com/matomo-org/matomo/pull/22013 enabling the same setting for MTM.

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

2024-03-17 21:31 UTC, caddoo approved these changes

2024-03-17 22:23 UTC, snake14 requested changes
Aside from the one change request, this looks like it should work. I did functional testing with the change that I suggested and it appeared to work as expected.

2024-03-17 22:23 UTC, snake14 commented on Template/Tag/MatomoTag.web.js
> +                    if (matomoConfig.disableCampaignParameters) {
I believe that this should match the name of the config created in `Template/Variable/MatomoConfigurationVariable.php`
```suggestion
                    if (matomoConfig.requireConsentForCampaignTracking) {
```

2024-03-17 22:33 UTC, michalkleiner commented on Template/Tag/MatomoTag.web.js
> +                    if (matomoConfig.disableCampaignParameters) {
Ok, thanks @snake14!

I wasn't sure as some of the other calls around this were referencing the methods and some were referencing the configs and I couldn't really find a pattern to follow. Will change this and see what the tests do. QA will test the overall change as well.

2024-03-17 23:04 UTC, snake14 approved these changes
Looks good to me :+1:

2024-03-18 00:03 UTC, AltamashShaikh approved these changes

2024-03-18 00:09 UTC, merged

2024-06-13 14:39 UTC, MatomoForumNotifications commented
This pull request has been mentioned on **Matomo forums**. There might be relevant details there:

https://forum.matomo.org/t/new-tracking-functions-disablecampaignparameters-enablecampaignparameters/58176/1